// ---------------------------------------------------------------------------
// Level 1 — Basic Business English. Original content authored for this seed.
// Compact DSL: w(word, pos, thai, definition, example, businessExample)
// ---------------------------------------------------------------------------

type Vocab = [string, string, string, string, string, string];

export interface ConvLine {
  speaker: string;
  text: string;
}

export interface L1Topic {
  title: string;
  desc: string;
  situation: string;
  dialogue: ConvLine[];
  expressions: string[];
  vocab: Vocab[];
}

export interface L1Course {
  title: string;
  short: string;
  desc: string;
  topics: L1Topic[];
}

const w = (
  word: string,
  pos: string,
  thai: string,
  def: string,
  ex: string,
  biz: string
): Vocab => [word, pos, thai, def, ex, biz];

export const level1 = {
  name: "Basic Business English",
  label: "Basic",
  slug: "basic",
  description:
    "Start from zero with everyday workplace English: greetings, introductions, personal information, simple requests, numbers, time, basic emails and your first office conversations.",
  courses: [
    {
      title: "Workplace Basics",
      short: "Greetings, introductions and first steps in the office",
      desc: "Learn the language you need on your first days in an English-speaking workplace: how to greet people, introduce yourself and colleagues, share basic personal information and use everyday office expressions.",
      topics: [
        {
          title: "Greetings at Work",
          desc: "Say hello and goodbye politely at different times of day.",
          situation: "It is 9:00 a.m. and you arrive at the office. Your colleague Susan is making coffee.",
          dialogue: [
            { speaker: "You", text: "Good morning, Susan. How are you today?" },
            { speaker: "Susan", text: "Good morning! I'm fine, thank you. And you?" },
            { speaker: "You", text: "I'm very well, thanks. How was your evening?" },
            { speaker: "Susan", text: "It was quiet. I watched TV and went to bed early." },
            { speaker: "You", text: "That sounds nice. Well, have a good day!" },
            { speaker: "Susan", text: "You too. See you later." },
          ],
          expressions: [
            "Good morning / Good afternoon / Good evening",
            "How are you? — I'm fine, thank you.",
            "Have a good day / See you later",
            "Nice to meet you",
          ],
          vocab: [
            w("greeting", "noun", "การทักทาย", "A friendly word said when you meet someone", "She gave everyone a warm greeting.", "Start emails with a polite greeting."),
            w("colleague", "noun", "เพื่อนร่วมงาน", "A person you work with", "My colleague helped me with the report.", "I usually have lunch with my colleagues."),
            w("arrive", "verb", "มาถึง", "To get to a place", "We arrive at the office at nine.", "Please arrive ten minutes before the meeting."),
            w("polite", "adjective", "สุภาพ", "Showing good manners", "It is polite to say thank you.", "Keep a polite tone in customer emails."),
            w("morning", "noun", "ตอนเช้า", "The early part of the day", "I check email every morning.", "The morning meeting starts at 9:30."),
            w("thanks", "noun", "ขอบคุณ", "A way to say thank you", "Thanks for your help.", "Thanks for the quick reply."),
            w("office", "noun", "สำนักงาน", "The place where people work", "The office is near the train station.", "Our new office has a big meeting room."),
            w("together", "adverb", "ด้วยกัน", "With each other", "We work together on Fridays.", "The team finished the project together."),
          ],
        },
        {
          title: "Introducing Yourself",
          desc: "Say your name, job and where you are from.",
          situation: "It is your first day at a new company. A manager asks you to introduce yourself to the team.",
          dialogue: [
            { speaker: "Manager", text: "Everyone, this is our new colleague. Please say hello." },
            { speaker: "You", text: "Hello everyone. My name is Napa." },
            { speaker: "Manager", text: "Nice to meet you, Napa. What do you do?" },
            { speaker: "You", text: "I'm a customer service assistant. I worked at a bank before." },
            { speaker: "Manager", text: "Great. We're happy to have you here." },
            { speaker: "You", text: "Thank you. I'm happy to be part of the team." },
          ],
          expressions: [
            "My name is… / I'm…",
            "I work as a… / I'm a…",
            "I'm from… / I live in…",
            "It's a pleasure to meet you",
          ],
          vocab: [
            w("introduce", "verb", "แนะนำ", "To tell someone your name or present another person", "Let me introduce myself.", "Allow me to introduce our new manager."),
            w("name", "noun", "ชื่อ", "The word people call you", "Please write your full name.", "Your name will appear on the certificate."),
            w("assistant", "noun", "ผู้ช่วย", "A person who helps someone at work", "She is the manager's assistant.", "He works as a sales assistant."),
            w("team", "noun", "ทีม", "A group of people who work together", "Our team meets every Monday.", "Welcome to the marketing team."),
            w("company", "noun", "บริษัท", "An organization that sells goods or services", "She works for a big company.", "Our company has offices in five countries."),
            w("before", "adverb", "ก่อนหน้านี้", "At an earlier time", "I worked in a hotel before.", "Did you work in sales before this job?"),
            w("experience", "noun", "ประสบการณ์", "Knowledge from doing something", "She has five years of experience.", "Experience with Excel is useful for this role."),
            w("pleasure", "noun", "ความยินดี", "A feeling of happiness or enjoyment", "It is a pleasure to work with you.", "It was a pleasure to meet you today."),
          ],
        },
        {
          title: "Introducing Colleagues",
          desc: "Present one person to another politely.",
          situation: "A client visits your office. You introduce the client to your project manager.",
          dialogue: [
            { speaker: "You", text: "Mr. Smith, I'd like to introduce our project manager, Khun Preecha." },
            { speaker: "You", text: "Preecha, this is Mr. Smith from Smith & Co." },
            { speaker: "Preecha", text: "How do you do, Mr. Smith? It's a pleasure." },
            { speaker: "Mr. Smith", text: "How do you do. Thank you for inviting me." },
            { speaker: "Preecha", text: "Shall we go to the meeting room for coffee?" },
            { speaker: "Mr. Smith", text: "Yes, please. After you." },
          ],
          expressions: [
            "I'd like to introduce…",
            "This is… from…",
            "How do you do? (formal first meeting)",
            "Have you met…?",
          ],
          vocab: [
            w("client", "noun", "ลูกค้า", "A person or company that buys your service", "The client wants a new contract.", "We met an important client today."),
            w("manager", "noun", "ผู้จัดการ", "A person who leads a team", "My manager approved the budget.", "The project manager set the deadline."),
            w("formal", "adjective", "เป็นทางการ", "Following official or polite rules", "Use formal language in first emails.", "This is a formal business letter."),
            w("invite", "verb", "เชิญ", "To ask someone to come", "They invited us to their office.", "We invited suppliers to the launch."),
            w("visit", "verb", "เยี่ยม", "To go and see a place or person", "A client visits our office today.", "She visits customers every month."),
            w("pleased", "adjective", "ยินดี", "Happy or glad", "We are pleased with the results.", "We are pleased to announce the new product."),
            w("together", "adverb", "ร่วมกัน", "In the same place at the same time", "The two teams worked together.", "Let's have lunch together tomorrow."),
            w("meeting room", "noun", "ห้องประชุม", "A room used for meetings", "The meeting room is on the second floor.", "Please book the meeting room for 2 p.m."),
          ],
        },
        {
          title: "Personal Information at Work",
          desc: "Share and check basic personal details safely.",
          situation: "A new colleague asks you to complete a staff information form.",
          dialogue: [
            { speaker: "Colleague", text: "Hi. Can I ask you some questions for the staff list?" },
            { speaker: "You", text: "Of course. What would you like to know?" },
            { speaker: "Colleague", text: "What is your full name, please?" },
            { speaker: "You", text: "My name is Napa Srisuwan." },
            { speaker: "Colleague", text: "And what is your email address?" },
            { speaker: "You", text: "It's napa.s@example.com." },
            { speaker: "Colleague", text: "Thank you. And your phone number?" },
            { speaker: "You", text: "My mobile number is 081-234-5678." },
          ],
          expressions: [
            "What is your full name?",
            "My email address is…",
            "Could you spell that, please?",
            "My phone number is…",
          ],
          vocab: [
            w("information", "noun", "ข้อมูล", "Facts about someone or something", "This form asks for personal information.", "Please provide your contact information."),
            w("address", "noun", "ที่อยู่", "The place where you live or work", "What is your email address?", "Please confirm your office address."),
            w("phone number", "noun", "เบอร์โทรศัพท์", "The number you call", "My phone number is on my card.", "Write your phone number on the form."),
            w("form", "noun", "แบบฟอร์ม", "A paper or page with spaces to write", "Please fill in this form.", "Complete the order form in English."),
            w("complete", "verb", "กรอกให้สมบูรณ์", "To finish something", "Complete the form before Friday.", "She completed the training course."),
            w("confirm", "verb", "ยืนยัน", "To say something is true or correct", "Please confirm your booking.", "Confirm the meeting time by email."),
            w("personal", "adjective", "ส่วนตัว", "About one person", "Keep personal details private.", "This is personal data; do not share it."),
            w("required", "adjective", "จำเป็นต้องมี", "Needed or demanded", "All fields are required.", "A work visa is required for this job."),
          ],
        },
        {
          title: "Office Expressions",
          desc: "Common polite phrases for daily office life.",
          situation: "You need help from a busy colleague during the day.",
          dialogue: [
            { speaker: "You", text: "Excuse me, are you busy right now?" },
            { speaker: "Colleague", text: "A little. What do you need?" },
            { speaker: "You", text: "Could you help me with the printer, please?" },
            { speaker: "Colleague", text: "Sure. No problem." },
            { speaker: "You", text: "Thank you very much. I appreciate it." },
            { speaker: "Colleague", text: "You're welcome. Anything else?" },
            { speaker: "You", text: "No, that's all. Thanks again." },
          ],
          expressions: [
            "Excuse me…",
            "Could you help me with…, please?",
            "No problem / Sure",
            "I appreciate it / You're welcome",
          ],
          vocab: [
            w("help", "verb", "ช่วยเหลือ", "To make something easier for someone", "Can you help me carry this box?", "Help is available at the front desk."),
            w("printer", "noun", "เครื่องพิมพ์", "A machine that prints paper", "The printer is out of paper.", "Please use the printer on floor two."),
            w("copy", "noun", "สำเนา", "A document made from another", "I need a copy of the invoice.", "Send a copy to the finance team."),
            w("excuse me", "phrase", "ขอโทษนะคะ/ครับ", "A polite way to start talking", "Excuse me, where is the restroom?", "Excuse me, could you repeat that?"),
            w("appreciate", "verb", "ซาบซึ้งใจ", "To be thankful for something", "I appreciate your help.", "We appreciate your quick response."),
            w("welcome", "adjective", "ยินดีต้อนรับ", "Received with pleasure", "You are welcome to join us.", "Welcome to the FactBusiness team."),
            w("trouble", "noun", "ปัญหา", "A problem or difficulty", "Sorry for the trouble.", "The machine is causing trouble again."),
            w("need", "verb", "ต้องการ", "To require something", "I need a new keyboard.", "We need more time for this task."),
          ],
        },
      ],
    },
    {
      title: "Business Introductions",
      short: "Talk about your job, your company and your role",
      desc: "Move from 'hello' to real business talk: describe your job title, your department, your responsibilities and your company, then make professional small talk.",
      topics: [
        {
          title: "Job Titles",
          desc: "Say and understand common job titles.",
          situation: "You attend a welcome event and meet people from other departments.",
          dialogue: [
            { speaker: "Person A", text: "Hi, I don't think we've met. I'm Dan from Sales." },
            { speaker: "You", text: "Nice to meet you, Dan. I'm Napa." },
            { speaker: "Person A", text: "What do you do at the company?" },
            { speaker: "You", text: "I'm an HR coordinator." },
            { speaker: "Person A", text: "Interesting. And who do you work with?" },
            { speaker: "You", text: "I support the HR manager with recruiting." },
          ],
          expressions: [
            "What do you do?",
            "I'm a… / I work in…",
            "I support the… manager",
            "I report to…",
          ],
          vocab: [
            w("title", "noun", "ตำแหน่งงาน", "The name of your job", "Her title is Marketing Manager.", "Write your job title on the name card."),
            w("department", "noun", "แผนก", "A section of a company", "She works in the finance department.", "The sales department is on floor five."),
            w("coordinator", "noun", "ผู้ประสานงาน", "A person who organizes activities", "The event coordinator booked the room.", "As coordinator, I manage the schedule."),
            w("sales", "noun", "ฝ่ายขาย", "Selling products or services", "Sales were strong this quarter.", "The sales team reached its target."),
            w("support", "verb", "สนับสนุน", "To help someone do their work", "I support three managers.", "Our team supports customers worldwide."),
            w("role", "noun", "บทบาท", "Your position or job", "Her role involves a lot of travel.", "In my new role, I lead a small team."),
            w("report to", "phrase", "ขึ้นตรงต่อ", "To have a manager above you", "I report to the regional director.", "All staff report to the office manager."),
            w("staff", "noun", "พนักงาน", "The people who work in a company", "The staff meeting starts at noon.", "We have forty staff in this office."),
          ],
        },
        {
          title: "Departments",
          desc: "Name departments and what they do.",
          situation: "A new supplier asks where different teams sit in your office.",
          dialogue: [
            { speaker: "Supplier", text: "Where is the purchasing team located?" },
            { speaker: "You", text: "Purchasing is on the third floor, next to finance." },
            { speaker: "Supplier", text: "And who handles the accounts?" },
            { speaker: "You", text: "The accounting department deals with payments." },
            { speaker: "Supplier", text: "Good. I need to deliver an invoice." },
            { speaker: "You", text: "You can give it to the receptionist on the ground floor." },
          ],
          expressions: [
            "Where is… located?",
            "The… department handles…",
            "Who deals with…?",
            "It's on the… floor",
          ],
          vocab: [
            w("finance", "noun", "การเงิน", "Managing money in a company", "Finance approves all budgets.", "The finance team closes the accounts monthly."),
            w("accounting", "noun", "การบัญชี", "Recording money movements", "Accounting prepares the tax report.", "She works in accounting."),
            w("purchasing", "noun", "จัดซื้อ", "Buying goods for the company", "Purchasing ordered new computers.", "Our purchasing policy needs two signatures."),
            w("receptionist", "noun", "พนักงานต้อนรับ", "The person who welcomes visitors", "The receptionist called me a taxi.", "Leave the parcel with the receptionist."),
            w("floor", "noun", "ชั้น", "A level of a building", "Our office is on the second floor.", "The cafeteria is on the top floor."),
            w("invoice", "noun", "ใบแจ้งหนี้", "A bill for goods or services", "Please pay this invoice by the 15th.", "Send the invoice to our accounts team."),
            w("budget", "noun", "งบประมาณ", "The money planned for something", "We have a small budget this year.", "The training budget was approved."),
            w("handle", "verb", "จัดการ", "To deal with something", "She handles customer questions.", "Who handles the daily orders?"),
          ],
        },
        {
          title: "Talking About Your Job",
          desc: "Describe your daily work and duties.",
          situation: "At lunch, a colleague from another branch asks about your routine.",
          dialogue: [
            { speaker: "Colleague", text: "So, what does a normal day look like for you?" },
            { speaker: "You", text: "I usually check emails first, then I update the orders." },
            { speaker: "Colleague", text: "Do you talk to customers much?" },
            { speaker: "You", text: "Yes, I answer customer questions on the phone." },
            { speaker: "Colleague", text: "That sounds busy. Do you enjoy it?" },
            { speaker: "You", text: "I do. I like helping people." },
          ],
          expressions: [
            "A normal day looks like…",
            "I usually… then I…",
            "My main duties are…",
            "I'm responsible for…",
          ],
          vocab: [
            w("duty", "noun", "หน้าที่", "Something you must do at work", "My duties include answering the phone.", "Cleaning duties rotate weekly."),
            w("responsible", "adjective", "รับผิดชอบ", "Having control over something", "I am responsible for the monthly report.", "She is responsible for training new staff."),
            w("usually", "adverb", "โดยปกติ", "Most of the time", "I usually start work at eight.", "We usually invoice at the end of the month."),
            w("routine", "noun", "กิจวัตร", "Things you do regularly", "My morning routine is the same every day.", "Establish a routine for checking reports."),
            w("task", "noun", "งานที่ได้รับมอบหมาย", "A piece of work to do", "I finished all my tasks early.", "The manager assigned three tasks to me."),
            w("deadline", "noun", "เส้นตายกำหนดส่ง", "The time when work must be finished", "The deadline is next Friday.", "We met the deadline with one day to spare."),
            w("answer", "verb", "ตอบ", "To reply to someone", "Answer the phone politely.", "She answers customer emails quickly."),
            w("work hours", "noun", "เวลาทำงาน", "The time you spend working", "My work hours are 9 to 6.", "Flexible work hours start next month."),
          ],
        },
        {
          title: "Talking About Your Company",
          desc: "Describe what your company does.",
          situation: "Your sister asks about the company where you started last month.",
          dialogue: [
            { speaker: "Sister", text: "Tell me about your new company. What do they do?" },
            { speaker: "You", text: "They make office furniture." },
            { speaker: "Sister", text: "Oh nice. How many people work there?" },
            { speaker: "You", text: "About two hundred, in three countries." },
            { speaker: "Sister", text: "And where is the head office?" },
            { speaker: "You", text: "It's in Bangkok, but I work in the branch in Chiang Mai." },
          ],
          expressions: [
            "The company makes / sells / provides…",
            "It has about… employees",
            "The head office is in…",
            "We export to…",
          ],
          vocab: [
            w("head office", "noun", "สำนักงานใหญ่", "The main office of a company", "Our head office is in the city center.", "Decisions come from the head office."),
            w("branch", "noun", "สาขา", "A local office of a company", "She works at the Silom branch.", "The bank has a branch in every province."),
            w("product", "noun", "ผลิตภัณฑ์", "Something a company sells", "Their main product is software.", "We launched a new product in March."),
            w("service", "noun", "บริการ", "Work done for customers", "They offer a cleaning service.", "Our service includes free delivery."),
            w("employee", "noun", "พนักงาน", "A person who works for a company", "The company has 500 employees.", "Employees receive a yearly bonus."),
            w("customer", "noun", "ลูกค้า", "A person who buys something", "The customer asked for a refund.", "Customer satisfaction is our priority."),
            w("export", "verb", "ส่งออก", "To sell goods to other countries", "They export rice to Europe.", "We export to Japan and Korea."),
            w("industry", "noun", "อุตสาหกรรม", "All companies in one type of business", "She works in the hotel industry.", "The car industry is growing fast."),
          ],
        },
        {
          title: "Professional Small Talk",
          desc: "Make polite conversation before a meeting.",
          situation: "You wait for a meeting to start with a client you met once.",
          dialogue: [
            { speaker: "Client", text: "Hello again. How was your trip to the office?" },
            { speaker: "You", text: "Very smooth, thank you. The traffic was light today." },
            { speaker: "Client", text: "Lucky you! Did you find the building easily?" },
            { speaker: "You", text: "Yes, your directions were perfect." },
            { speaker: "Client", text: "Would you like some coffee while we wait?" },
            { speaker: "You", text: "Yes, please. Black with no sugar." },
          ],
          expressions: [
            "How was your trip / weekend?",
            "The traffic was light / heavy",
            "Would you like some coffee?",
            "Black with no sugar, please",
          ],
          vocab: [
            w("small talk", "noun", "พูดคุยเรื่องทั่วไป", "Polite conversation about unimportant things", "We made small talk before the meeting.", "A little small talk builds trust with clients."),
            w("trip", "noun", "การเดินทาง", "A journey to a place", "The trip took two hours.", "She is on a business trip in Singapore."),
            w("traffic", "noun", "การจราจร", "Cars moving on roads", "The traffic is bad at 6 p.m.", "Avoid the city during rush hour traffic."),
            w("directions", "noun", "เส้นทาง", "Instructions on how to get somewhere", "He gave me directions to the hotel.", "The map app shows clear directions."),
            w("weather", "noun", "สภาพอากาศ", "Sun, rain, wind, temperature", "The weather is nice today.", "People often talk about the weather."),
            w("weekend", "noun", "สุดสัปดาห์", "Saturday and Sunday", "What did you do on the weekend?", "I relax with my family at the weekend."),
            w("comfortable", "adjective", "สบาย", "Feeling relaxed and at ease", "Make yourself comfortable.", "Is the chair comfortable?"),
            w("conversation", "noun", "บทสนทนา", "Talk between people", "We had a short conversation.", "Keep the conversation professional."),
          ],
        },
      ],
    },
    {
      title: "Office Communication",
      short: "Ask questions, make requests and give answers",
      desc: "The core language of office communication: asking simple questions, making polite requests, answering clearly and describing daily routines.",
      topics: [
        {
          title: "Workplace Vocabulary Basics",
          desc: "Learn the first 10 words of daily office life.",
          situation: "You join an orientation tour of the office.",
          dialogue: [
            { speaker: "Guide", text: "This is the supply room. You can find paper and pens here." },
            { speaker: "You", text: "Great. Where do we collect the mail?" },
            { speaker: "Guide", text: "The mail room is next to the stairs." },
            { speaker: "You", text: "And what about the meeting rooms?" },
            { speaker: "Guide", text: "You can book them on the computer by the entrance." },
          ],
          expressions: [
            "Where can I find…?",
            "You can book… on…",
            "It's next to / opposite / near…",
            "Could you show me…?",
          ],
          vocab: [
            w("supply room", "noun", "ห้องเก็บของ", "A room for office materials", "Take new pens from the supply room.", "The supply room needs more paper."),
            w("mail", "noun", "จดหมาย", "Letters and parcels", "The mail arrives at ten.", "Please send the contract by mail."),
            w("desk", "noun", "โต๊ะทำงาน", "A table for working", "My desk is by the window.", "Keep your desk clean and tidy."),
            w("computer", "noun", "คอมพิวเตอร์", "A machine for working on", "Turn off your computer at night.", "The IT team set up my new computer."),
            w("book", "verb", "จอง", "To reserve something", "I booked a meeting room for two.", "Book a hotel room for the client."),
            w("entrance", "noun", "ทางเข้า", "The door to go in", "The entrance is on the left.", "Visitors wait at the main entrance."),
            w("paper", "noun", "กระดาษ", "Thin sheets for writing or printing", "We printed the report on A4 paper.", "The paper tray is empty again."),
            w("drawer", "noun", "ลิ้นชัก", "A sliding box in a desk", "The keys are in the top drawer.", "Files are kept in the cabinet drawer."),
          ],
        },
        {
          title: "Asking Simple Questions",
          desc: "Ask about things and places politely.",
          situation: "You are new and you ask a senior colleague how things work.",
          dialogue: [
            { speaker: "You", text: "Excuse me, when is the lunch break?" },
            { speaker: "Senior", text: "Lunch is from twelve to one." },
            { speaker: "You", text: "And where can I get a name card?" },
            { speaker: "Senior", text: "Ask the receptionist; she orders them." },
            { speaker: "You", text: "One more question: how do I request leave?" },
            { speaker: "Senior", text: "Fill in the leave form and send it to HR." },
          ],
          expressions: [
            "When is…? / Where is…?",
            "How do I…?",
            "Who can I ask about…?",
            "What time does…?",
          ],
          vocab: [
            w("question", "noun", "คำถาม", "Something you ask", "Do you have any questions?", "Good questions show interest."),
            w("lunch break", "noun", "พักเที่ยง", "Time off for lunch", "The lunch break is one hour.", "I eat quickly during the lunch break."),
            w("leave", "noun", "การลา", "Time away from work", "I need to take leave next week.", "Apply for annual leave in advance."),
            w("request", "noun/verb", "ขอ", "To ask for something politely", "She made a request for a new chair.", "Please request approval before buying."),
            w("name card", "noun", "นามบัตร", "A small card with your details", "He gave me his name card.", "Exchange name cards at the start of meetings."),
            w("policy", "noun", "นโยบาย", "Official rules of a company", "The dress policy is smart casual.", "Read the leave policy carefully."),
            w("approve", "verb", "อนุมัติ", "To officially agree to something", "My manager approved my leave.", "Finance must approve the invoice."),
            w("advice", "noun", "คำแนะนำ", "Helpful suggestions", "Ask HR for advice on the policy.", "Her advice saved us time."),
          ],
        },
        {
          title: "Making Simple Requests",
          desc: "Ask people to do things politely.",
          situation: "Your computer stops working and you need help.",
          dialogue: [
            { speaker: "You", text: "Could you take a look at my computer, please?" },
            { speaker: "IT", text: "Sure. What's the problem?" },
            { speaker: "You", text: "The screen is black and nothing opens." },
            { speaker: "IT", text: "Let me check. Can you wait a few minutes?" },
            { speaker: "You", text: "Of course. Thank you." },
            { speaker: "IT", text: "It's fixed — try restarting it now." },
          ],
          expressions: [
            "Could you…, please?",
            "Can you…? / Would you mind…?",
            "Would it be possible to…?",
            "Of course / Certainly",
          ],
          vocab: [
            w("request", "phrase", "ขอร้อง", "Polite asking", "This is a formal request for leave.", "He made a request for more staff."),
            w("restart", "verb", "รีสตาร์ท", "To start a computer again", "Restart the computer after the update.", "IT said to restart the router."),
            w("screen", "noun", "จอภาพ", "The display of a computer", "The screen is too bright.", "Share your screen in the meeting."),
            w("check", "verb", "ตรวจสอบ", "To look at something carefully", "Check the report for mistakes.", "Please check the delivery date."),
            w("fix", "verb", "ซ่อม", "To repair something", "The technician fixed the phone.", "We fixed the error in the file."),
            w("wait", "verb", "รอ", "To stay until something happens", "Please wait a moment.", "The client is waiting in reception."),
            w("certainly", "adverb", "แน่นอน", "Yes, of course", "Certainly, I can help with that.", "We will certainly deliver on time."),
            w("trouble", "noun", "ปัญหา", "Problems or difficulty", "We are having trouble with the wifi.", "Sorry for any trouble this causes."),
          ],
        },
        {
          title: "Giving Basic Answers",
          desc: "Answer clearly, confirm and apologize politely.",
          situation: "A colleague calls to check a delivery time you confirmed earlier.",
          dialogue: [
            { speaker: "Colleague", text: "Hi, is the delivery still at three o'clock?" },
            { speaker: "You", text: "Yes, that's correct. The truck arrives at three." },
            { speaker: "Colleague", text: "And did you receive the documents?" },
            { speaker: "You", text: "Not yet. I'll check and call you back." },
            { speaker: "Colleague", text: "No problem. Thanks for confirming." },
            { speaker: "You", text: "My pleasure. Talk soon." },
          ],
          expressions: [
            "Yes, that's correct.",
            "Not yet, but I'll…",
            "Let me check and call you back.",
            "Sorry, I don't know. I'll find out.",
          ],
          vocab: [
            w("correct", "adjective", "ถูกต้อง", "Right or true", "Your answer is correct.", "Please confirm the correct price."),
            w("delivery", "noun", "การจัดส่ง", "Bringing goods to a place", "Delivery takes two days.", "The delivery arrived on time."),
            w("receive", "verb", "ได้รับ", "To get something", "Did you receive my email?", "We received your order yesterday."),
            w("documents", "noun", "เอกสาร", "Official papers", "Sign the documents and return them.", "All documents are in the folder."),
            w("confirm", "verb", "ยืนยัน", "To make sure something is true", "Can you confirm the date?", "The hotel confirmed our booking."),
            w("apologize", "verb", "ขอโทษ", "To say sorry", "I apologize for the delay.", "We apologize for the mistake."),
            w("understand", "verb", "เข้าใจ", "To know what something means", "I understand your question.", "We understand the customer's problem."),
            w("soon", "adverb", "เร็วๆ นี้", "In a short time", "I will send it soon.", "The new stock arrives soon."),
          ],
        },
        {
          title: "Daily Office Routines",
          desc: "Describe what you do every day at work.",
          situation: "An exchange student follows you for a day to learn about office life.",
          dialogue: [
            { speaker: "Student", text: "What do you do when you arrive in the morning?" },
            { speaker: "You", text: "First I make coffee, then I read my emails." },
            { speaker: "Student", text: "What happens at ten o'clock?" },
            { speaker: "You", text: "We have a short team stand-up meeting." },
            { speaker: "Student", text: "And after lunch?" },
            { speaker: "You", text: "I usually call clients in the afternoon." },
          ],
          expressions: [
            "First I…, then I…",
            "We have a… every morning",
            "After lunch I usually…",
            "On Fridays we…",
          ],
          vocab: [
            w("routine", "adjective", "กิจวัตรประจำ", "Done regularly", "Routine work is easy to plan.", "We follow the same routine daily."),
            w("meeting", "noun", "การประชุม", "People meeting to talk about work", "The meeting starts at ten.", "I have back-to-back meetings today."),
            w("schedule", "noun", "ตารางเวลา", "A plan of times", "My schedule is full this week.", "Check the meeting schedule online."),
            w("calendar", "noun", "ปฏิทิน", "A chart of days and months", "I put the deadline in my calendar.", "She manages the team calendar."),
            w("prepare", "verb", "เตรียม", "To make something ready", "Prepare the slides before the meeting.", "The kitchen staff prepare lunch daily."),
            w("finish", "verb", "เสร็จ", "To complete something", "I finish work at six.", "When will you finish the report?"),
            w("break", "noun", "พัก", "A short rest", "Take a ten-minute break.", "The coffee break is at three."),
            w("report", "noun", "รายงาน", "A document with information", "Write a short report on sales.", "The monthly report is due Friday."),
          ],
        },
      ],
    },
    {
      title: "Telephone English",
      short: "Answer calls, take messages and arrange callbacks",
      desc: "Essential phone English: starting and ending calls, taking messages, spelling names and numbers, and handling simple problems.",
      topics: [
        {
          title: "Basic Telephone Phrases",
          desc: "Open and close a phone call professionally.",
          situation: "You answer the phone at reception.",
          dialogue: [
            { speaker: "Caller", text: "Hello, is this Siam Office Supplies?" },
            { speaker: "You", text: "Yes, good morning. Siam Office Supplies, how can I help you?" },
            { speaker: "Caller", text: "I'd like to speak to the sales team, please." },
            { speaker: "You", text: "One moment, I'll put you through." },
            { speaker: "Caller", text: "Thank you." },
            { speaker: "You", text: "You're welcome. Please hold." },
          ],
          expressions: [
            "Good morning. [Company], how can I help you?",
            "I'd like to speak to…, please.",
            "One moment, I'll put you through.",
            "I'm sorry, the line is busy.",
          ],
          vocab: [
            w("phone call", "noun", "โทรศัพท์", "Talking to someone on the phone", "I have a phone call at noon.", "Return the client's phone call today."),
            w("caller", "noun", "ผู้โทร", "A person making a call", "The caller is waiting.", "Ask the caller to spell their name."),
            w("reception", "noun", "แผนกต้อนรับ", "The desk where visitors first go", "Call reception for a taxi.", "Leave the package at reception."),
            w("speak to", "phrase", "พูดกับ", "To talk with someone", "May I speak to the manager?", "She spoke to the supplier for an hour."),
            w("hold", "verb", "ถือสายรอ", "To wait on the phone", "Please hold for a moment.", "The caller held for two minutes."),
            w("line", "noun", "สาย", "A telephone connection", "The line is busy right now.", "Please stay on the line."),
            w("message", "noun", "ข้อความ", "Information left for someone", "Can I take a message?", "She left a message for you."),
            w("available", "adjective", "ว่าง", "Free to talk or meet", "The manager is not available now.", "Is the consultant available this afternoon?"),
          ],
        },
        {
          title: "Taking a Message",
          desc: "Write down and repeat messages correctly.",
          situation: "The manager is away and an important client calls.",
          dialogue: [
            { speaker: "Client", text: "Can I speak to Ms. Chan, please?" },
            { speaker: "You", text: "I'm afraid she's in a meeting. Can I take a message?" },
            { speaker: "Client", text: "Yes. Please tell her that Mr. Lee called." },
            { speaker: "You", text: "Certainly. Could you spell your name, please?" },
            { speaker: "Client", text: "L-E-E. Lee." },
            { speaker: "You", text: "Thank you, Mr. Lee. And your number?" },
            { speaker: "Client", text: "092-111-2233." },
            { speaker: "You", text: "Let me repeat that: 092-111-2233. I'll give her the message." },
          ],
          expressions: [
            "I'm afraid she's in a meeting.",
            "Can I take a message?",
            "Could you spell that, please?",
            "Let me repeat that to confirm.",
          ],
          vocab: [
            w("message", "noun", "ข้อความฝากไว้", "Information left for a person", "Take a message while she is away.", "The message says the meeting moved."),
            w("spell", "verb", "สะกด", "To say the letters of a word", "How do you spell your surname?", "Spell the product code slowly."),
            w("repeat", "verb", "พูดซ้ำ", "To say again", "Could you repeat the number?", "Repeat the order back to the customer."),
            w("afraid", "adjective", "เกรงว่า", "Sorry to say (polite)", "I'm afraid the file is missing.", "We are afraid the price has changed."),
            w("urgent", "adjective", "ด่วน", "Needing action now", "This is an urgent request.", "Mark urgent emails in red."),
            w("call back", "phrase", "โทรกลับ", "To phone someone again later", "I'll call you back in an hour.", "She called back after lunch."),
            w("note", "noun", "บันทึก", "A short written reminder", "I made a note of the date.", "Keep a note of the call time."),
            w("return", "verb", "ตอบกลับ", "To give back or reply", "Return the call as soon as possible.", "He returned the missed call quickly."),
          ],
        },
        {
          title: "Numbers and Spelling on the Phone",
          desc: "Say numbers, prices and codes clearly.",
          situation: "You give your order number and confirm a price on the phone.",
          dialogue: [
            { speaker: "You", text: "Our order number is 4587, please." },
            { speaker: "Supplier", text: "Is that four-five-eight-seven?" },
            { speaker: "You", text: "Correct. And the total is one thousand two hundred baht." },
            { speaker: "Supplier", text: "One thousand two hundred. Fine. Payment by bank transfer?" },
            { speaker: "You", text: "Yes. Our account name is B-A-N-K-O-K business, one word." },
          ],
          expressions: [
            "That's 4-5-8-7.",
            "The total is…",
            "Pay by bank transfer / credit card",
            "Let me read it back to you.",
          ],
          vocab: [
            w("number", "noun", "ตัวเลข", "A symbol for a count", "Read the numbers clearly.", "The order number is on the box."),
            w("total", "noun", "ยอดรวม", "The final amount", "The total is 2,500 baht.", "The total includes tax."),
            w("amount", "noun", "จำนวนเงิน", "How much money", "The amount is written below.", "Confirm the amount before paying."),
            w("price", "noun", "ราคา", "The money you pay", "The price includes delivery.", "Prices rise every January."),
            w("bank transfer", "noun", "โอนเงินผ่านธนาคาร", "Moving money between accounts", "We paid by bank transfer.", "Bank transfer takes one day."),
            w("account", "noun", "บัญชี", "A record of money with a bank", "What is your account number?", "The invoice shows our account details."),
            w("code", "noun", "รหัส", "Letters or numbers with meaning", "Enter the product code.", "The discount code is on the flyer."),
            w("confirm", "verb", "ยืนยันอีกครั้ง", "To double-check something", "Confirm the figures by phone.", "Please confirm receipt of this email."),
          ],
        },
        {
          title: "Arranging a Call",
          desc: "Agree on a good time to talk.",
          situation: "A partner in another time zone wants to schedule a call.",
          dialogue: [
            { speaker: "Partner", text: "Is this a good time to talk about the contract?" },
            { speaker: "You", text: "Actually, I have a meeting in five minutes." },
            { speaker: "Partner", text: "No problem. When would suit you?" },
            { speaker: "You", text: "Would tomorrow at ten work for you?" },
            { speaker: "Partner", text: "Ten is fine for me. I'll call you then." },
            { speaker: "You", text: "Perfect. I'll send a calendar invite." },
          ],
          expressions: [
            "Is this a good time to talk?",
            "When would suit you?",
            "Would tomorrow at 10 work for you?",
            "I'll send a calendar invite.",
          ],
          vocab: [
            w("arrange", "verb", "จัดตาราง", "To plan something", "Arrange a call with the client.", "We arranged a visit for Monday."),
            w("suit", "verb", "สะดวก", "To be convenient for someone", "Does three o'clock suit you?", "Choose a time that suits everyone."),
            w("convenient", "adjective", "สะดวก", "Easy or suitable", "Is Thursday convenient for you?", "Morning calls are more convenient for us."),
            w("time zone", "noun", "เขตเวลา", "A region with the same time", "The call crosses two time zones.", "Check the time zone before calling abroad."),
            w("invite", "noun", "คำเชิญ", "A request to attend", "Accept the calendar invite.", "She sent an invite to the webinar."),
            w("schedule", "verb", "กำหนดเวลา", "To plan a time for something", "Schedule the call for Tuesday.", "We scheduled the review for noon."),
            w("delay", "noun", "ความล่าช้า", "When something is late", "The call started after a short delay.", "Apologize for any delay in reply."),
            w("appointment", "noun", "นัดหมาย", "An arranged meeting time", "I have an appointment at two.", "The dentist's appointment is next week."),
          ],
        },
        {
          title: "Telephone Problem Phrases",
          desc: "Handle bad lines and misunderstandings.",
          situation: "A connection is bad and you cannot hear the supplier.",
          dialogue: [
            { speaker: "Supplier", text: "Can you hear me? The line is breaking up." },
            { speaker: "You", text: "Sorry, I didn't catch that. Could you say it again?" },
            { speaker: "Supplier", text: "I said the parts arrive on Friday." },
            { speaker: "You", text: "Friday — got it. You're very clear now." },
            { speaker: "Supplier", text: "Great. I'll send the tracking number by email." },
            { speaker: "You", text: "Perfect. Speak to you soon." },
          ],
          expressions: [
            "Sorry, you're breaking up.",
            "I didn't catch that. Could you say it again?",
            "Could you speak a little more slowly?",
            "Let me confirm: you said Friday, correct?",
          ],
          vocab: [
            w("catch", "verb", "ได้ยินชัด", "To hear or understand", "I didn't catch your name.", "Did you catch the order number?"),
            w("connection", "noun", "สัญญาณ", "The phone or internet link", "The connection is poor today.", "We lost the connection mid-call."),
            w("clear", "adjective", "ชัดเจน", "Easy to hear or understand", "Your voice is very clear now.", "Keep the message short and clear."),
            w("slowly", "adverb", "ช้าๆ", "Not fast", "Please speak slowly.", "Read the terms slowly and carefully."),
            w("tracking", "noun", "การติดตามพัสดุ", "Following a parcel's journey", "The tracking number is on the site.", "Tracking shows delivery tomorrow."),
            w("misunderstanding", "noun", "ความเข้าใจผิด", "When people understand wrongly", "The mix-up was a misunderstanding.", "Repeat details to avoid misunderstandings."),
            w("hang up", "phrase", "วางสาย", "To end a call", "Please don't hang up yet.", "She hung up without saying goodbye."),
            w("volume", "noun", "ระดับเสียง", "How loud something is", "Turn up the phone volume.", "Check the volume on your headset."),
          ],
        },
      ],
    },
    {
      title: "Basic Emails",
      short: "Write clear, polite short emails in English",
      desc: "Learn a simple email structure you can reuse: clear subject lines, polite openings, short sentences, a clear request and a friendly ending.",
      topics: [
        {
          title: "Email Structure",
          desc: "The five parts of a good business email.",
          situation: "Your manager asks you to email a supplier for the first time.",
          dialogue: [
            { speaker: "Manager", text: "Please write a short email to our supplier." },
            { speaker: "You", text: "What should I include?" },
            { speaker: "Manager", text: "A clear subject, a greeting, why you write, and what you need." },
            { speaker: "You", text: "And how should I end it?" },
            { speaker: "Manager", text: "Close with 'Best regards' and your name and title." },
          ],
          expressions: [
            "Subject: Order #4587 — delivery question",
            "Dear Ms. Kim, / Hello Khun Somchai,",
            "I am writing to ask about…",
            "Best regards, / Kind regards,",
          ],
          vocab: [
            w("subject", "noun", "หัวข้ออีเมล", "The title line of an email", "Write a clear subject line.", "The subject says 'Invoice attached'."),
            w("email", "noun", "อีเมล", "A digital letter", "Send the file by email.", "Check your email twice a day."),
            w("attachment", "noun", "ไฟล์แนบ", "A file sent with an email", "Please find the attachment.", "The attachment is the price list."),
            w("Dear", "adjective", "เรียน/ถึง", "The formal start of a letter", "Dear Ms. Kim, thank you for your order.", "Use 'Dear' with the person's name."),
            w("regards", "noun", "ด้วยความเคารพ", "A polite email ending", "Best regards, Napa.", "Kind regards is formal but friendly."),
            w("paragraph", "noun", "ย่อหน้า", "A block of sentences", "Keep each paragraph short.", "One idea per paragraph is best."),
            w("signature", "noun", "ลายเซ็นท้ายอีเมล", "Your name and contact at the end", "Add your job title to your signature.", "The email signature shows our logo."),
            w("reply", "noun/verb", "ตอบกลับ", "An answer to a message", "I will reply within one day.", "Thanks for your quick reply."),
          ],
        },
        {
          title: "Greetings and Sign-offs",
          desc: "Open and close emails with the right formality.",
          situation: "You learn which email openings match which relationships.",
          dialogue: [
            { speaker: "Colleague", text: "How should I start an email to a new client?" },
            { speaker: "You", text: "Use 'Dear Mr. or Ms.' plus their family name." },
            { speaker: "Colleague", text: "And to someone I know well?" },
            { speaker: "You", text: "Then 'Hi' plus their first name is fine." },
            { speaker: "Colleague", text: "What about the ending?" },
            { speaker: "You", text: "'Best regards' works for most business emails." },
          ],
          expressions: [
            "Dear Mr. Smith / Dear Ms. Jones",
            "Hi Preecha, / Hello team,",
            "Yours sincerely (formal letter)",
            "Best regards / Thanks",
          ],
          vocab: [
            w("surname", "noun", "นามสกุล", "Your family name", "Use the surname with 'Mr.' or 'Ms.'", "Please spell your surname."),
            w("formal", "adjective", "เป็นทางการ", "Very polite and official", "New clients get formal emails.", "Formal letters use 'Dear'."),
            w("informal", "adjective", "ไม่เป็นทางการ", "Relaxed and friendly", "Use informal English with close teammates.", "Keep it informal but professional."),
            w("polite", "adjective", "สุภาพ", "Respectful and kind", "Polite emails get faster replies.", "A polite closing is important."),
            w("sincerely", "adverb", "ด้วยความจริงใจ", "A formal letter ending", "Yours sincerely closes formal letters.", "Sign 'Sincerely' when you know the name."),
            w("tone", "noun", "น้ำเสียง", "The feeling of your words", "Keep a friendly tone in emails.", "A short email can sound rude — check the tone."),
            w("colleague", "noun", "เพื่อนร่วมงาน", "Someone at your work", "Email your colleagues about the change.", "She is a close colleague of mine."),
            w("sign off", "phrase", "ลงท้าย", "To end a message with your name", "Sign off with your full name.", "Sign off before the attachment list."),
          ],
        },
        {
          title: "Time and Dates in Emails",
          desc: "Write times and dates correctly in English.",
          situation: "You set a meeting time in an email to a foreign partner.",
          dialogue: [
            { speaker: "Partner", text: "Can we move the meeting to next Tuesday?" },
            { speaker: "You", text: "Of course. Which time works for you?" },
            { speaker: "Partner", text: "Ten thirty in the morning, your time." },
            { speaker: "You", text: "So Tuesday the 14th at 10:30 a.m." },
            { speaker: "Partner", text: "Exactly. I'll update the invite." },
          ],
          expressions: [
            "Tuesday, 14 May at 10:30 a.m.",
            "Let's meet next week.",
            "I'm available on… / I'm free at…",
            "Does that work for you?",
          ],
          vocab: [
            w("date", "noun", "วันที่", "A specific day", "Write the date at the top.", "The delivery date is confirmed."),
            w("month", "noun", "เดือน", "One of twelve parts of a year", "Sales were high last month.", "The report covers last month."),
            w("o'clock", "adverb", "นาฬิกา", "Exact hour", "The call starts at three o'clock.", "Lunch is at twelve o'clock."),
            w("a.m.", "adverb", "ช่วงเช้า", "Before noon", "The meeting is at 9 a.m.", "Open at 8 a.m. sharp."),
            w("p.m.", "adverb", "ช่วงบ่าย/เย็น", "After noon", "We close at 6 p.m.", "The flight leaves at 4 p.m."),
            w("deadline", "noun", "กำหนดส่ง", "The last time allowed", "The email deadline is Friday.", "Send before the deadline."),
            w("quarter", "noun", "ไตรมาส", "Three months of the year", "Sales grew in the first quarter.", "The quarterly report is due in April."),
            w("calendar", "noun", "ปฏิทิน", "A system of days and months", "Check your calendar for free days.", "The event calendar is on the intranet."),
          ],
        },
        {
          title: "Simple Request Emails",
          desc: "Ask for information or action by email.",
          situation: "You need a price list from a supplier.",
          dialogue: [
            { speaker: "Manager", text: "Did you ask about the new price list?" },
            { speaker: "You", text: "Not yet. I'll send a short request now." },
            { speaker: "Manager", text: "Remember to say why you need it." },
            { speaker: "You", text: "I'll say we are comparing prices for next year." },
            { speaker: "Manager", text: "And set a clear date for the reply." },
            { speaker: "You", text: "I'll ask for it by the end of the week." },
          ],
          expressions: [
            "Could you send me…?",
            "I would appreciate it if you could…",
            "Could you let me know by Friday?",
            "Please find attached…",
          ],
          vocab: [
            w("enquiry", "noun", "การสอบถาม", "A question about something", "We received an enquiry about prices.", "Send the enquiry to the sales desk."),
            w("compare", "verb", "เปรียบเทียบ", "To look at how things are similar or different", "Compare the two offers first.", "We compared prices with three suppliers."),
            w("quotation", "noun", "ใบเสนอราคา", "A written price offer", "Please send a quotation for 100 units.", "The quotation is valid for 30 days."),
            w("response", "noun", "การตอบกลับ", "An answer", "We are waiting for their response.", "The response rate was high."),
            w("appreciate", "verb", "ขอบคุณล่วงหน้า", "To be grateful", "I would appreciate a quick reply.", "We appreciate your continued business."),
            w("regarding", "preposition", "เกี่ยวกับ", "About something", "I write regarding the invoice.", "Questions regarding the order? Contact us."),
            w("forward", "verb", "ส่งต่อ", "To send an email to another person", "Forward the email to finance.", "Please forward the file to the team."),
            w("urgently", "adverb", "อย่างเร่งด่วน", "Very quickly", "We urgently need the documents.", "The package is needed urgently."),
          ],
        },
        {
          title: "Replying to an Email",
          desc: "Answer quickly, clearly and politely.",
          situation: "A customer emailed to ask about delivery times.",
          dialogue: [
            { speaker: "Customer", text: "I emailed about my order. Did you reply?" },
            { speaker: "You", text: "Yes, I sent the answer this morning." },
            { speaker: "Customer", text: "You said delivery takes three days?" },
            { speaker: "You", text: "Correct. It will arrive by Thursday." },
            { speaker: "Customer", text: "Perfect. Thanks for the fast reply." },
          ],
          expressions: [
            "Thank you for your email.",
            "In reply to your question, yes, we can.",
            "I will look into it and get back to you.",
            "Please do not hesitate to ask.",
          ],
          vocab: [
            w("acknowledge", "verb", "รับทราบ", "To say you received something", "Please acknowledge this email.", "We acknowledge your request."),
            w("receive", "verb", "ได้รับ", "To get something sent", "Did you receive my previous email?", "We received your message yesterday."),
            w("clarify", "verb", "ทำให้ชัดเจน", "To explain more clearly", "Could you clarify the delivery terms?", "Let me clarify what I meant."),
            w("further", "adjective", "เพิ่มเติม", "More or additional", "I will update you with further details.", "No further action is needed."),
            w("hesitate", "verb", "ลังเล", "To wait because you are unsure", "Do not hesitate to contact me.", "Don't hesitate to ask questions."),
            w("look into", "phrase", "ตรวจสอบเรื่อง", "To investigate", "I will look into the problem.", "IT is looking into the error."),
            w("solution", "noun", "ทางแก้", "A way to solve a problem", "We found a simple solution.", "The solution was to update the file."),
            w("as soon as possible", "phrase", "โดยเร็วที่สุด", "Very quickly (ASAP)", "Send the report ASAP.", "We will reply as soon as possible."),
          ],
        },
      ],
    },
    {
      title: "Meetings Basics",
      short: "Join and understand your first business meetings",
      desc: "The language of simple meetings: starting, asking for opinions, agreeing politely, managing time and closing clearly.",
      topics: [
        {
          title: "Meeting Vocabulary",
          desc: "Key words used in every meeting.",
          situation: "Your first team meeting is on Monday. A friend explains the terms.",
          dialogue: [
            { speaker: "Friend", text: "What is on the meeting agenda?" },
            { speaker: "You", text: "We will talk about the new schedule." },
            { speaker: "Friend", text: "Who is leading the meeting?" },
            { speaker: "You", text: "The team leader, Khun Aom." },
            { speaker: "Friend", text: "Take notes so you remember the action points." },
            { speaker: "You", text: "Good idea. I'll bring a notebook." },
          ],
          expressions: [
            "What's on the agenda?",
            "Who is chairing the meeting?",
            "Let's take notes on the action points.",
            "Could you send me the minutes?",
          ],
          vocab: [
            w("agenda", "noun", "วาระการประชุม", "The list of topics for a meeting", "The agenda has five items.", "Send the agenda before the meeting."),
            w("meeting", "noun", "การประชุม", "A planned discussion", "The meeting lasts one hour.", "We had a productive meeting."),
            w("minutes", "noun", "รายงานการประชุม", "The written record of a meeting", "Who will write the minutes?", "The minutes were shared by email."),
            w("attend", "verb", "เข้าร่วม", "To be present at something", "Twelve people attended the meeting.", "All managers attend the monthly review."),
            w("chair", "verb", "เป็นประธาน", "To lead a meeting", "Khun Aom chairs the meeting.", "The chair opened the discussion."),
            w("item", "noun", "วาระ", "One topic on an agenda", "The first item is the budget.", "We skipped item three."),
            w("participant", "noun", "ผู้เข้าร่วม", "A person in a meeting", "Each participant received a handout.", "Participants joined from three cities."),
            w("conference room", "noun", "ห้องประชุมใหญ่", "A room for large meetings", "The conference room holds 20 people.", "Book the conference room for Friday."),
          ],
        },
        {
          title: "Starting a Meeting",
          desc: "Open a meeting politely and on time.",
          situation: "You must start the weekly team meeting.",
          dialogue: [
            { speaker: "You", text: "Good morning, everyone. Shall we get started?" },
            { speaker: "Team", text: "Yes, let's begin." },
            { speaker: "You", text: "First, let's look at last week's sales." },
            { speaker: "Dan", text: "I have the numbers here." },
            { speaker: "You", text: "Great. Dan, could you share them?" },
            { speaker: "Dan", text: "Sure. Sales were up ten percent." },
          ],
          expressions: [
            "Shall we get started?",
            "Let's begin with…",
            "First, let's look at…",
            "Our goal today is to…",
          ],
          vocab: [
            w("start", "verb", "เริ่ม", "To begin something", "We start meetings on time.", "The training starts at nine."),
            w("goal", "noun", "เป้าหมาย", "What you want to achieve", "Our goal today is clear.", "The sales goal for this year is high."),
            w("topic", "noun", "หัวข้อ", "The subject of discussion", "The main topic is the budget.", "Stay on topic during meetings."),
            w("welcome", "verb", "ต้อนรับ", "To greet someone happily", "Welcome everyone to today's meeting.", "We welcome new ideas."),
            w("begin", "verb", "เริ่มต้น", "To start", "Let's begin with item one.", "The presentation begins at two."),
            w("share", "verb", "แบ่งปัน", "To give others part of something", "Could you share the results?", "Share the file with the whole team."),
            w("update", "noun", "อัปเดตสถานะ", "News about progress", "Give us a quick update on the project.", "The weekly update is on Friday."),
            w("announcement", "noun", "ประกาศ", "Official news", "There is an announcement about the office move.", "The CEO made a short announcement."),
          ],
        },
        {
          title: "Asking for Opinions",
          desc: "Ask others what they think politely.",
          situation: "You want the team's views on a new plan.",
          dialogue: [
            { speaker: "You", text: "What do you think about the new plan?" },
            { speaker: "Aom", text: "I think it's a good start." },
            { speaker: "You", text: "Does anyone have a different opinion?" },
            { speaker: "Dan", text: "I have one concern about the timing." },
            { speaker: "You", text: "Good point. Let's discuss that." },
            { speaker: "Dan", text: "Maybe we can start one week later." },
          ],
          expressions: [
            "What do you think about…?",
            "In my opinion,…",
            "Does anyone have a different view?",
            "That's an interesting point.",
          ],
          vocab: [
            w("opinion", "noun", "ความคิดเห็น", "What a person thinks", "Give us your opinion.", "Opinions differ on this plan."),
            w("view", "noun", "มุมมอง", "A way of thinking about something", "From my view, the price is fair.", "Share your view with the team."),
            w("suggest", "verb", "เสนอแนะ", "To offer an idea", "I suggest we meet weekly.", "She suggested a cheaper supplier."),
            w("agree", "verb", "เห็นด้วย", "To have the same opinion", "I agree with Dan.", "We all agreed on the deadline."),
            w("disagree", "verb", "ไม่เห็นด้วย", "To have a different opinion", "I disagree with that decision.", "It's okay to disagree politely."),
            w("concern", "noun", "ข้อกังวล", "A worry about something", "My concern is the cost.", "The client raised a concern."),
            w("decision", "noun", "การตัดสินใจ", "A final choice", "The decision was unanimous.", "We made the decision today."),
            w("point", "noun", "ประเด็น", "An idea in discussion", "That's a very good point.", "The main point is quality."),
          ],
        },
        {
          title: "Agreeing and Thanking",
          desc: "Show agreement and thanks in meetings.",
          situation: "The team agrees with your suggestion and thanks you.",
          dialogue: [
            { speaker: "You", text: "What if we send the survey this week?" },
            { speaker: "Aom", text: "That sounds like a good idea." },
            { speaker: "Dan", text: "I agree completely." },
            { speaker: "You", text: "Great, then it's settled." },
            { speaker: "Aom", text: "Thanks for the suggestion, Napa." },
            { speaker: "You", text: "You're welcome. Happy to help." },
          ],
          expressions: [
            "That sounds like a good idea.",
            "I agree completely.",
            "I couldn't agree more.",
            "Then it's settled.",
          ],
          vocab: [
            w("agree", "verb", "เห็นด้วย", "To share the same view", "We agree on the main points.", "The partners agreed on the price."),
            w("completely", "adverb", "อย่างสิ้นเชิง", "Totally", "I completely agree with you.", "The system was completely updated."),
            w("settled", "adjective", "ตกลงแล้ว", "Decided and final", "The date is settled.", "Once it's settled, we inform everyone."),
            w("suggestion", "noun", "ข้อเสนอ", "An idea you give", "Thanks for your suggestion.", "The best suggestion won the vote."),
            w("grateful", "adjective", "รู้สึกขอบคุณ", "Feeling thanks", "We are grateful for your support.", "She was grateful for the feedback."),
            w("thank", "verb", "ขอบคุณ", "To say thanks", "Thank you all for coming.", "Thank the customer for their time."),
            w("support", "noun", "การสนับสนุน", "Help and encouragement", "Thank you for your support.", "The team showed great support."),
            w("contribution", "noun", "การมีส่วนร่วม", "Something you add or give", "Your contribution helped a lot.", "Every contribution counts."),
          ],
        },
        {
          title: "Ending a Meeting",
          desc: "Close clearly and list next steps.",
          situation: "The meeting is almost over and you summarize the plan.",
          dialogue: [
            { speaker: "You", text: "Let's summarize what we agreed." },
            { speaker: "Aom", text: "We will send the survey on Monday." },
            { speaker: "Dan", text: "And I will prepare the slides." },
            { speaker: "You", text: "Perfect. We meet again next week." },
            { speaker: "Aom", text: "Same time, same room?" },
            { speaker: "You", text: "Yes. Thank you all for coming." },
          ],
          expressions: [
            "Let's summarize what we agreed.",
            "To sum up,…",
            "Our next steps are…",
            "Thank you all for coming.",
          ],
          vocab: [
            w("summarize", "verb", "สรุป", "To say the main points briefly", "Summarize the meeting in three lines.", "She summarized the report for the boss."),
            w("next steps", "noun", "ขั้นตอนต่อไป", "The actions that come next", "Our next steps are clear.", "Email the team with the next steps."),
            w("follow up", "phrase", "ติดตามผล", "To check progress later", "I will follow up next week.", "Follow up on the invoice today."),
            w("close", "verb", "ปิดการประชุม", "To end something", "Let's close the meeting here.", "The office closes at six."),
            w("action", "noun", "การดำเนินการ", "Something that is done", "Each action has an owner.", "The action list is short."),
            w("remind", "verb", "เตือน", "To help someone remember", "Remind me to send the file.", "The system reminds us of deadlines."),
            w("available", "adjective", "สะดวก", "Free to meet", "I am available on Friday.", "The room is available after three."),
            w("summary", "noun", "บทสรุป", "A short version of something", "Send a summary to everyone.", "The summary was one page long."),
          ],
        },
      ],
    },
    {
      title: "Business Vocabulary",
      short: "Numbers, time, dates and core office nouns",
      desc: "Build your first active business vocabulary: numbers, times, dates, schedules and the most common office nouns and verbs.",
      topics: [
        {
          title: "Numbers in Business",
          desc: "Read and say business numbers confidently.",
          situation: "You prepare a table of figures for your manager.",
          dialogue: [
            { speaker: "Manager", text: "How many units did we sell in January?" },
            { speaker: "You", text: "We sold one thousand two hundred units." },
            { speaker: "Manager", text: "And what was the revenue?" },
            { speaker: "You", text: "Revenue was about three hundred fifty thousand baht." },
            { speaker: "Manager", text: "Good. Please put the figures in the report." },
          ],
          expressions: [
            "1,200 = one thousand two hundred",
            "350,000 = three hundred fifty thousand",
            "Growth of ten percent",
            "Sales doubled / fell by half",
          ],
          vocab: [
            w("figure", "noun", "ตัวเลข/ยอด", "A number in a report", "Check the figures twice.", "The sales figures are strong."),
            w("percent", "noun", "เปอร์เซ็นต์", "Out of one hundred", "Sales grew by ten percent.", "A five percent discount applies."),
            w("unit", "noun", "ชิ้น/หน่วย", "One item of a product", "We shipped 500 units.", "The price per unit is 80 baht."),
            w("revenue", "noun", "รายได้", "Money a company earns", "Revenue rose this quarter.", "Revenue minus costs equals profit."),
            w("growth", "noun", "การเติบโต", "Getting bigger", "The company shows steady growth.", "Growth slowed in the second half."),
            w("double", "verb", "เพิ่มเป็นสองเท่า", "To become twice as big", "Profits doubled last year.", "We doubled our output."),
            w("average", "noun", "ค่าเฉลี่ย", "The middle number of a group", "The average order is 2,000 baht.", "On average, we get 50 calls a day."),
            w("total", "noun", "ยอดรวม", "The final sum", "The total for the month is 1.2 million.", "Add the totals for each region."),
          ],
        },
        {
          title: "Time Expressions",
          desc: "Use common time phrases at work.",
          situation: "A colleague asks about your schedule for the day.",
          dialogue: [
            { speaker: "Colleague", text: "Are you free at half past ten?" },
            { speaker: "You", text: "Let me check. Yes, ten thirty works." },
            { speaker: "Colleague", text: "Great. It will take about twenty minutes." },
            { speaker: "You", text: "Fine. Right after that I have lunch." },
            { speaker: "Colleague", text: "Perfect. See you at ten thirty." },
          ],
          expressions: [
            "half past ten = 10:30",
            "a quarter to three = 2:45",
            "right away / in a moment",
            "It takes about twenty minutes",
          ],
          vocab: [
            w("quarter", "noun", "15 นาที", "Fifteen minutes", "Come back in a quarter of an hour.", "The meeting starts at quarter past nine."),
            w("half", "noun", "ครึ่ง", "Thirty minutes (of an hour)", "I'll call at half past two.", "Take a half-hour break."),
            w("duration", "noun", "ระยะเวลา", "How long something lasts", "The duration of the call is 20 minutes.", "Keep the duration short."),
            w("punctual", "adjective", "ตรงเวลา", "On time", "Be punctual for client meetings.", "She is always punctual."),
            w("early", "adverb", "เช้า/ก่อนเวลา", "Before the expected time", "Arrive ten minutes early.", "The flight left early."),
            w("late", "adverb", "สาย", "After the expected time", "Do not be late for work.", "The shipment arrived late."),
            w("rush hour", "noun", "ชั่วโมงเร่งด่วน", "Busy traffic time", "Avoid travel in the rush hour.", "Leave before the rush hour."),
            w("moment", "noun", "ครู่หนึ่ง", "A very short time", "Please wait a moment.", "One moment, please."),
          ],
        },
        {
          title: "Days, Dates and Schedules",
          desc: "Talk about plans and deadlines by date.",
          situation: "You plan a training week with the organizer.",
          dialogue: [
            { speaker: "Organizer", text: "The training is on the fourteenth of May." },
            { speaker: "You", text: "Is that a Tuesday?" },
            { speaker: "Organizer", text: "Yes. It runs from Monday the thirteenth to Friday." },
            { speaker: "You", text: "And the schedule for each day?" },
            { speaker: "Organizer", text: "Nine to four with an hour for lunch." },
            { speaker: "You", text: "Perfect. Please save me a place." },
          ],
          expressions: [
            "Monday to Friday",
            "the fourteenth of May / May the 14th",
            "from nine to four",
            "by the end of the month",
          ],
          vocab: [
            w("daily", "adjective", "รายวัน", "Every day", "Send a daily sales update.", "The daily report is at 5 p.m."),
            w("weekly", "adjective", "รายสัปดาห์", "Every week", "We hold a weekly review.", "The weekly meeting is on Mondays."),
            w("monthly", "adjective", "รายเดือน", "Every month", "The monthly bill arrives on the first.", "Submit the monthly timesheet."),
            w("yearly", "adjective", "รายปี", "Every year", "The yearly holiday closes the office.", "The yearly budget is set in November."),
            w("fortnight", "noun", "สองสัปดาห์", "Two weeks", "The course runs for a fortnight.", "We invoice every fortnight."),
            w("schedule", "noun", "ตาราง", "A plan with times", "The schedule changed today.", "Print the bus schedule."),
            w("book in advance", "phrase", "จองล่วงหน้า", "To reserve early", "Book the hotel in advance.", "Seats sell out, so book in advance."),
            w("postpone", "verb", "เลื่อนออกไป", "To move to a later time", "We postponed the launch.", "The event was postponed to June."),
          ],
        },
        {
          title: "Common Office Nouns",
          desc: "Name everyday objects around the office.",
          situation: "You help a new intern find things in the office.",
          dialogue: [
            { speaker: "Intern", text: "Where can I find a stapler?" },
            { speaker: "You", text: "In the drawer under the printer." },
            { speaker: "Intern", text: "And filing folders?" },
            { speaker: "You", text: "The cabinet next to the photocopier." },
            { speaker: "Intern", text: "Thanks. One more — the scanner?" },
            { speaker: "You", text: "IT set it up beside your desk." },
          ],
          expressions: [
            "Where can I find…?",
            "It's in / on / under / next to…",
            "Ask… for it.",
            "Let me show you.",
          ],
          vocab: [
            w("stapler", "noun", "เครื่องเย็บกระดาษ", "A tool that joins papers", "Borrow the stapler from the desk.", "The stapler is in the supply room."),
            w("folder", "noun", "แฟ้ม", "A holder for papers or files", "Keep each client in a folder.", "The folders are labeled by month."),
            w("cabinet", "noun", "ตู้", "Furniture with drawers or doors", "The files are in the metal cabinet.", "Lock the cabinet at night."),
            w("scanner", "noun", "เครื่องสแกน", "A machine that copies images to computer", "Scan the contract with the scanner.", "Use the scanner for the ID card."),
            w("notebook", "noun", "สมุดบันทึก", "A book for writing notes", "Write ideas in your notebook.", "Bring a notebook to the meeting."),
            w("whiteboard", "noun", "กระดานไวท์บอร์ด", "A board you write on with markers", "Draw the plan on the whiteboard.", "The whiteboard is in the meeting room."),
            w("headset", "noun", "หูฟัง", "Headphones with a microphone", "Use a headset for online calls.", "The headset helps you hear clearly."),
            w("filing", "noun", "การจัดเก็บเอกสาร", "Organizing documents", "Filing takes an hour each week.", "The filing system is alphabetical."),
          ],
        },
        {
          title: "Communication Verbs",
          desc: "Verbs you use every day to communicate.",
          situation: "Your manager explains how to keep everyone informed.",
          dialogue: [
            { speaker: "Manager", text: "Please notify the team about the room change." },
            { speaker: "You", text: "Should I email them or tell them in person?" },
            { speaker: "Manager", text: "Send an email and also mention it at stand-up." },
            { speaker: "You", text: "Got it. I'll announce it this morning." },
            { speaker: "Manager", text: "Perfect. Keep me updated if anyone asks." },
          ],
          expressions: [
            "Please notify… / inform…",
            "Let me announce…",
            "Keep me updated.",
            "Let's discuss it later.",
          ],
          vocab: [
            w("notify", "verb", "แจ้งให้ทราบ", "To officially tell someone", "Notify staff about the drill.", "We notified customers by email."),
            w("inform", "verb", "แจ้ง", "To give information to someone", "Please inform the client of the delay.", "Keep me informed of any changes."),
            w("announce", "verb", "ประกาศ", "To tell many people officially", "They announced the new CEO.", "We will announce the winner on Friday."),
            w("discuss", "verb", "หารือ", "To talk about something", "Let's discuss the budget later.", "We discussed the issue with HR."),
            w("mention", "verb", "กล่าวถึง", "To say something briefly", "He mentioned the new policy.", "Please mention the discount in your email."),
            w("explain", "verb", "อธิบาย", "To make something clear", "Explain the process step by step.", "The guide explained the safety rules."),
            w("remind", "verb", "เตือน", "To make someone remember", "Remind staff about the training.", "The app reminds me of meetings."),
            w("ask", "verb", "ถาม", "To request information", "Ask the client for their preference.", "Don't be afraid to ask questions."),
          ],
        },
      ],
    },
    {
      title: "Daily Workplace English",
      short: "Everyday conversations with your team",
      desc: "Practice natural daily English: morning chats, describing your work, break-time small talk and wrapping up the day.",
      topics: [
        {
          title: "Morning at the Office",
          desc: "Start your day with natural office chat.",
          situation: "You arrive and meet colleagues at the coffee machine.",
          dialogue: [
            { speaker: "You", text: "Good morning! Busy day ahead?" },
            { speaker: "Colleague", text: "Pretty busy. We're finishing the report today." },
            { speaker: "You", text: "I can help if you need an extra pair of hands." },
            { speaker: "Colleague", text: "That's very kind. Maybe after lunch?" },
            { speaker: "You", text: "Sure. Just call me when you're ready." },
            { speaker: "Colleague", text: "Will do. Thanks a lot." },
          ],
          expressions: [
            "Busy day ahead?",
            "I can help if you need…",
            "Just call me when you're ready.",
            "Sounds good / Will do",
          ],
          vocab: [
            w("busy", "adjective", "ยุ่ง", "Having a lot to do", "I'm busy until three.", "Monday is always busy."),
            w("ahead", "adverb", "ข้างหน้า", "In the future", "We have a busy week ahead.", "Plan the work ahead."),
            w("finish", "verb", "ทำเสร็จ", "To complete", "Finish the draft by noon.", "She finished the training yesterday."),
            w("help", "noun", "ความช่วยเหลือ", "Assistance", "Thanks for the help.", "We need extra help this week."),
            w("ready", "adjective", "พร้อม", "Prepared", "I'm ready to start.", "Is the report ready?"),
            w("kind", "adjective", "ใจดี", "Nice and helpful", "That's very kind of you.", "Thank you for your kind words."),
            w("start", "verb", "เริ่มงาน", "To begin", "We start at 8:30.", "The new hire starts on Monday."),
            w("energy", "noun", "พลังงาน", "Strength to work", "Coffee gives me energy.", "The team has great energy today."),
          ],
        },
        {
          title: "Describing Daily Work",
          desc: "Talk about what you do step by step.",
          situation: "A new trainee asks what your department does all day.",
          dialogue: [
            { speaker: "Trainee", text: "What does your team do every day?" },
            { speaker: "You", text: "We check orders, contact suppliers and update the system." },
            { speaker: "Trainee", text: "How many orders a day?" },
            { speaker: "You", text: "Around sixty on a normal day." },
            { speaker: "Trainee", text: "That's a lot. Do you work in shifts?" },
            { speaker: "You", text: "No, we all work the same hours." },
          ],
          expressions: [
            "We check…, contact… and update…",
            "On a normal day…",
            "Around sixty orders.",
            "We work in shifts / same hours.",
          ],
          vocab: [
            w("process", "verb", "ดำเนินการ", "To handle step by step", "We process orders daily.", "The application takes three days to process."),
            w("update", "verb", "อัปเดต", "To make current", "Update the customer list.", "The system updates overnight."),
            w("shift", "noun", "กะ", "A period of work", "The night shift ends at six.", "She works the morning shift."),
            w("normal", "adjective", "ปกติ", "Usual or ordinary", "A normal day starts at nine.", "Normal delivery takes two days."),
            w("contact", "verb", "ติดต่อ", "To reach someone", "Contact us by phone or email.", "We contacted all suppliers."),
            w("efficient", "adjective", "มีประสิทธิภาพ", "Working well without waste", "The new system is more efficient.", "Keep emails short and efficient."),
            w("manage", "verb", "จัดการ", "To control or organize", "She manages the stock room.", "Manage your time carefully."),
            w("organize", "verb", "จัดระเบียบ", "To arrange in order", "Organize the files by date.", "She organized the team lunch."),
          ],
        },
        {
          title: "Break-Time Talk",
          desc: "Relaxed conversation during breaks.",
          situation: "You take a coffee break with two colleagues.",
          dialogue: [
            { speaker: "Colleague 1", text: "Whew, I needed this break." },
            { speaker: "You", text: "Me too. It's been a long morning." },
            { speaker: "Colleague 2", text: "Did you try the new cafe across the street?" },
            { speaker: "You", text: "Not yet. Is the coffee good?" },
            { speaker: "Colleague 2", text: "It's great, and the service is fast." },
            { speaker: "You", text: "Let's go together tomorrow, then." },
          ],
          expressions: [
            "I needed this break.",
            "It's been a long morning.",
            "Did you try…?",
            "Let's go together.",
          ],
          vocab: [
            w("break", "noun", "พักเบรก", "A short rest from work", "Take a break every two hours.", "The afternoon break is at three."),
            w("rest", "noun", "การพักผ่อน", "Relaxing time", "You need some rest.", "Rest is important for focus."),
            w("chat", "verb", "คุยเล่น", "To talk informally", "We chatted about the weekend.", "Chat with new colleagues at lunch."),
            w("relax", "verb", "ผ่อนคลาย", "To rest and calm down", "Relax for a few minutes.", "The lounge is a place to relax."),
            w("cafe", "noun", "ร้านกาแฟ", "A coffee shop", "Meet me at the cafe.", "The cafe near the office is cheap."),
            w("enjoy", "verb", "เพลิดเพลิน", "To like something", "Enjoy your lunch break.", "I enjoy working with this team."),
            w("laugh", "verb", "หัวเราะ", "To make happy sounds", "We laughed at the story.", "Laughter makes teams closer."),
            w("fresh", "adjective", "สดชื่น", "New and cool", "Get some fresh air at noon.", "Fresh ideas come from breaks."),
          ],
        },
        {
          title: "End-of-Day Conversations",
          desc: "Wrap up the day and plan tomorrow.",
          situation: "It's 5:30 p.m. and people are leaving the office.",
          dialogue: [
            { speaker: "Colleague", text: "Are you heading off?" },
            { speaker: "You", text: "Almost — I just need to send one more email." },
            { speaker: "Colleague", text: "Okay. Did you finish the report?" },
            { speaker: "You", text: "Yes, it's done. I'll send it tonight." },
            { speaker: "Colleague", text: "Great. See you tomorrow, then." },
            { speaker: "You", text: "See you! Have a good evening." },
          ],
          expressions: [
            "Are you heading off?",
            "I just need to…",
            "See you tomorrow.",
            "Have a good evening.",
          ],
          vocab: [
            w("leave", "verb", "ออกจากที่ทำงาน", "To go away from work", "I leave at six.", "Leave early on Fridays."),
            w("evening", "noun", "ช่วงเย็น", "The later part of the day", "Have a nice evening.", "The evening shift starts at six."),
            w("tomorrow", "noun", "พรุ่งนี้", "The day after today", "See you tomorrow.", "The meeting is tomorrow at ten."),
            w("tonight", "adverb", "คืนนี้", "This evening", "I'll finish it tonight.", "Send the draft tonight if you can."),
            w("tired", "adjective", "เหนื่อย", "Needing rest", "I'm tired after the long day.", "Don't work when you're too tired."),
            w("plan", "verb", "วางแผน", "To decide what to do", "Plan tomorrow's tasks now.", "We planned the launch carefully."),
            w("check off", "phrase", "ขีดออก", "To mark as done", "Check off each finished task.", "Check off the items on the list."),
            w("task list", "noun", "รายการงาน", "A list of things to do", "My task list is empty — done!", "Keep a daily task list."),
          ],
        },
        {
          title: "Weekly Review Chat",
          desc: "Review your week with your manager.",
          situation: "Friday afternoon: your manager asks about your week.",
          dialogue: [
            { speaker: "Manager", text: "How was your week, Napa?" },
            { speaker: "You", text: "Very productive. I finished the customer list." },
            { speaker: "Manager", text: "Great. Any problems?" },
            { speaker: "You", text: "One supplier was late, but we solved it." },
            { speaker: "Manager", text: "Nice work. Anything you need for next week?" },
            { speaker: "You", text: "Just more training on the new software." },
          ],
          expressions: [
            "How was your week?",
            "Very productive / quite busy",
            "We solved it.",
            "Anything you need?",
          ],
          vocab: [
            w("productive", "adjective", "เกิดผล", "Getting a lot done", "It was a productive week.", "Short meetings are more productive."),
            w("solve", "verb", "แก้ปัญหา", "To find an answer to a problem", "We solved the delivery issue.", "IT solved the login problem."),
            w("review", "noun", "การทบทวน", "A look back at progress", "The weekly review is short.", "Review your work before sending."),
            w("improve", "verb", "ปรับปรุง", "To make better", "Improve your typing speed.", "Sales improved in May."),
            w("progress", "noun", "ความคืบหน้า", "Moving forward", "We made good progress.", "Track your progress weekly."),
            w("issue", "noun", "ปัญหา", "A problem to solve", "There was an issue with the printer.", "The issue is now resolved."),
            w("achieve", "verb", "บรรลุ", "To succeed in doing", "We achieved our monthly target.", "She achieved the sales goal."),
            w("reflect", "verb", "ทบทวนตนเอง", "To think about what happened", "Reflect on what went well.", "Take time to reflect each week."),
          ],
        },
      ],
    },
  ],
} as const satisfies {
  name: string;
  label: string;
  slug: string;
  description: string;
  courses: L1Course[];
};
